# Generated by Django 5.2.3 on 2025-06-21 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('patient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('right_sphere', models.FloatField(default=0.0)),
                ('right_cylinder', models.FloatField(default=0.0)),
                ('right_axis', models.IntegerField(default=0)),
                ('left_sphere', models.FloatField(default=0.0)),
                ('left_cylinder', models.FloatField(default=0.0)),
                ('left_axis', models.IntegerField(default=0)),
                ('pupillary_distance', models.IntegerField()),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], default='active', max_length=10)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='issued_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
