# Generated by Django 5.2.2 on 2025-06-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='availability',
            field=models.JSONField(default=list),
        ),
    ]
