# Generated by Django 5.2.3 on 2025-06-13 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='areas_of_expertise',
            new_name='availability',
        ),
    ]
