# Generated by Django 5.2.2 on 2025-06-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctorprofile_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
